// <auto-generated />
using System;
using BlogMvc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlogMvc.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191019172429_datetime")]
    partial class datetime
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlogMvc.Models.CategoryModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName");

                    b.HasKey("ID");

                    b.ToTable("Category");

                    b.HasData(
                        new { ID = 1, CategoryName = "Freddie Kitchens" },
                        new { ID = 2, CategoryName = "Baker Mayfield" },
                        new { ID = 3, CategoryName = "Nick Chubb" },
                        new { ID = 4, CategoryName = "2019 Schedule" }
                    );
                });

            modelBuilder.Entity("BlogMvc.Models.PostModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author");

                    b.Property<string>("Body");

                    b.Property<int?>("CategoriesID");

                    b.Property<int>("CategoryID");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Image");

                    b.Property<int>("TagID");

                    b.Property<int?>("TagsID");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.HasIndex("CategoriesID");

                    b.HasIndex("TagsID");

                    b.ToTable("Post");

                    b.HasData(
                        new { ID = 1, Author = "BK", Body = "Kitchens’ thick Southern drawl hugs every syllable that flows from his mouth. But don’t mistake Kitchens for a dolt.  18 years after coaching for Saban, Kitchens has slowly worked his way up the ladder to become an NFL head coach. Kitchens coached for four other teams between his time with LSU and the Browns. He spent all of that time as either a quarterbacks coach, running backs coach, or tight ends coach.", CategoryID = 1, Date = new DateTime(2019, 10, 19, 13, 24, 28, 979, DateTimeKind.Local), Image = "/Images1/FredK1.jpg", TagID = 1, Title = "Impressions so far on Freddie Kitchens" },
                        new { ID = 2, Author = "BK", Body = "What’s wrong? Well, just about everything. When an offense faceplants to this degree, there isn’t just one culprit. But let’s start with versatility in personnel groupings. Per Sharp Football Analysis, the Browns are running 11 personnel (one running back, one tight end, three wide receivers) on 84% of their offensive snaps. That’s one of the highest rates in the NFL, and in line with the Rams as Sean McVay has become the king of 11 personnel. In fact, the Rams, who ran 11 personnel on 94% of their plays last season, are running it just 83% of the time in 2019, as McVay endeavors to upset defenses who have stacked their schemes to counter his previous predictability.", CategoryID = 1, Date = new DateTime(2019, 10, 19, 13, 24, 28, 981, DateTimeKind.Local), Image = "/Images1/BakerM1.jpg", TagID = 1, Title = "What's Wrong with Baker?" },
                        new { ID = 3, Author = "BK", Body = "As a standout track & field athlete, Chubb competed from 2011 to 2015 in events ranging from the 100-meters to the shot put. At the 2013 4A Sectionals, he took fifth place in the long jump event with a leap of 6.85 meters (22 ft, 4 in).[3] At the 2014 4A Sectionals, he won the shot put event, recording a top-throw of 17.05 meters (55 ft, 8in), and earned second-place finishes in both the 100-meter dash, with a time of 10.69 seconds (setting a school record), and the 200-meter dash, with a time of 21.83 seconds.[4] He captured the state title in the shot put at the 2014 Class AAAA with a throw of 16.77 meters (55 ft).", CategoryID = 1, Date = new DateTime(2019, 10, 19, 13, 24, 28, 981, DateTimeKind.Local), Image = "/Images1/NickC1.jpg", TagID = 1, Title = "Lookout NFL... Nick Chubb is a beast!" },
                        new { ID = 4, Author = "BK", Body = "This is the game Breech listed as the make-or-break game for the Browns, and I agree wholeheartedly. Everyone is assuming the Browns are going to steamroll the Titans because the Titans are boring and the Browns are the Hansel of the NFL. The Browns are a 5.5-point favorite over Tennessee at home. The Browns have been 5.5-point favorites eight times in the last 15 years. They covered three of those games. I'm not saying they won't win the game or even not cover, but the hype is cascading out of control on this team. The Titans nearly made the playoffs last year, have an underrated roster, will try to come in and pound the ball with Derrick Henry and could steal this game. It would send shockwaves through Cleveland if Tennessee pulled off the upset. ", CategoryID = 1, Date = new DateTime(2019, 10, 19, 13, 24, 28, 981, DateTimeKind.Local), Image = "/Images1/BSched1.jpg", TagID = 1, Title = "The Browns Schedule is not very friendly" }
                    );
                });

            modelBuilder.Entity("BlogMvc.Models.TagModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TagName");

                    b.HasKey("ID");

                    b.ToTable("Tag");

                    b.HasData(
                        new { ID = 1, TagName = "Freddie Kitchens" },
                        new { ID = 2, TagName = "Baker Mayfield" },
                        new { ID = 3, TagName = "Nick Chubb" },
                        new { ID = 4, TagName = "2019 Schedule" }
                    );
                });

            modelBuilder.Entity("BlogMvc.Models.PostModel", b =>
                {
                    b.HasOne("BlogMvc.Models.CategoryModel", "Categories")
                        .WithMany("Posts")
                        .HasForeignKey("CategoriesID");

                    b.HasOne("BlogMvc.Models.TagModel", "Tags")
                        .WithMany("Posts")
                        .HasForeignKey("TagsID");
                });
#pragma warning restore 612, 618
        }
    }
}
